name: CustomizablePlayerModels
version: ${version}
description: Customizable Player Models server-side plugin.
author: tom5454
website: https://github.com/tom5454/CustomPlayerModels
main: com.tom.cpm.paper.CPMPaperPlugin
api-version: "1.21"
permissions:
  cpm.*:
    children:
      cpm.command: true
  cpm.command:
    default: op
    description: access to cpm command
folia-supported: true